# Generated by Django 4.2.3 on 2023-08-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_elevator_elevatorrequests_elevatorfunctionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorrequests',
            name='req_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
