# Generated by Django 4.2.3 on 2023-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_elevatorforrequests_elevatorfromrequests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorforrequests',
            name='count_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
