# Generated by Django 4.2.3 on 2023-08-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_elevatorforrequests_count_of_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevatorforrequests',
            old_name='req_time',
            new_name='reqTime',
        ),
    ]
