# Generated by Django 4.2.3 on 2023-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_rename_req_time_elevatorfromrequests_reqtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatorfromrequests',
            name='count_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
