# Generated by Django 4.2.3 on 2023-08-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0008_elevatorfromrequests_count_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorforrequests',
            name='elevator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_for', to='elevator.elevator'),
        ),
    ]
