from .elevator.views import ElevatorFunctionalityViewSet, ElevatorNextDestinationViewSet, FullFilElevatorNextRequestsViewSet
from .floor.views import FloorViewSet
from .elevatorForRequests.views import RequestForElevatorViewSet, AllRequestsForElevatorViewSet
from .elevatorFromRequest.views import RequestFromElevatorViewSet, AllRequestsFromElevatorViewSet
from .elevatorFunctionality.views import ElevatorFunctionalityDoorViewSet, ElevatorFunctionalityMovingViewSet, ElevatorFunctionalityOperationalViewSet
