# from rest_framework import serializers

from .serializer.modelSerializers.serializers import FloorSerializer, ElevatorSerializer, ElevatorFunctionalitySerializer, ElevatorForRequestsSerializer, ElevatorFromRequestsSerializer
from .serializer.contractSerializers.serializers import ElevatorFunctionalityMovingSerializer, ElevatorFunctionalityOperationalSerializer, ElevatorFunctionalityDoorSerializer, ElevatorNextDestinationSerializer, FulFillElevatorsNextRequestsSerializer
