# from rest_framework import serializers

from .modelSerializers.serializers import FloorSerializer, ElevatorSerializer, ElevatorFunctionalitySerializer, ElevatorForRequestsSerializer, ElevatorFromRequestsSerializer
from .contractSerializers.serializers import ElevatorFunctionalityMovingSerializer, ElevatorFunctionalityOperationalSerializer, ElevatorFunctionalityDoorSerializer, ElevatorNextDestinationSerializer, FullFilElevatorNextRequestsSerializer
