# Generated by Django 4.2.3 on 2023-07-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Start', 'Start'), ('Stop', 'Stop'), ('Running', 'Running')], max_length=10)),
            ],
        ),
    ]
