# Generated by Django 4.2.3 on 2023-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSeeding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movements',
            name='action',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
