# Generated by Django 4.2.3 on 2023-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSeeding', '0002_doorfunctions_alter_movements_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
