# Generated by Django 4.2.3 on 2023-07-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSeeding', '0003_moving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operational_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
