# Generated by Django 4.2.3 on 2023-08-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_elevatorforrequests_elevatorfromrequests_and_more'),
        ('dataSeeding', '0006_elevatorrequeststatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElevatorRequestType',
        ),
    ]
